AllCops:
  Exclude:
    - config/environments/development.rb
    - config/initializers/devise.rb

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
  Exclude:
    - app/channels/application_cable/connection.rb
    - app/channels/application_cable/channel.rb
    - config/application.rb

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/**/*

Metrics/AbcSize:
  Enabled: false
